pulseview/devicemanager.cpp: use full namespace for _1 & _2 placeholders
Newer boost seems to cause an ambiguous reference for the _1 & _2
placeholders.

Error is:
```
scopy/src/pulseview/pv/devicemanager.cpp:107:60: error: reference to '_1' is ambiguous
        devices_.sort(bind(&DeviceManager::compare_devices, this, _1, _2));
                                                                  ^
scopy/src/pulseview/pv/devicemanager.cpp:44:26: note: candidate found by name lookup is '_1'
using std::placeholders::_1;
                         ^
/local/include/boost/bind/placeholders.hpp:46:38: note: candidate found by name lookup is 'boost::placeholders::_1'
BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
```

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>